services:
  backend:
    build: http_server
    environment:
      - CLUSTERED_DATA_PATH=/app/clustered_orig.csv
    volumes:
      - ./clustered_orig.csv:/app/clustered_orig.csv
  tg_bot:
    build: bot
    env_file:
      - path: ./.env
        required: true
    environment:
      - BACKEND_FQDN=backend
    depends_on:
      - backend
